
```{r}
library(shiny)
library(tidyverse)
library(shinythemes)
```



```{r}
library(vroom)
library(neiss)
```

```{r}
top_prod <- injuries %>%
  filter(trmt_date >= as.Date("2017-01-01"), trmt_date < as.Date("2018-01-01")) %>%
  count(prod1, sort = TRUE) %>%
  filter(n > 5 * 365)

injuries <- injuries %>%
  filter(trmt_date >= as.Date("2017-01-01"), trmt_date < as.Date("2018-01-01")) %>%
  semi_join(top_prod, by = "prod1") %>%
  mutate(age = floor(age), sex = tolower(sex), race = tolower(race)) %>%
  filter(sex != "unknown") %>%
  select(trmt_date, age, sex, race, body_part, diag, location, prod_code = prod1, weight, narrative) 
```



```{r}
head(injuries)
```

```{r}
products <- products %>%
  semi_join(top_prod, by = c("code" = "prod1")) %>%
  rename(prod_code = code)
```



```{r}
population <- population %>%
  filter(year == 2017) %>%
  select(-year) %>%
  rename(population = n) 

```

```{r}
selected <- injuries %>% filter(prod_code == 1842)
nrow(selected)
```


```{r}
selected %>% count(diag, wt = weight, sort = TRUE)

```



```{r}
selected %>% count(body_part, wt = weight, sort = TRUE)

```

```{r}
selected %>% count(location, wt = weight, sort = TRUE)

```



```{r}
summary <- selected %>%  count(age, sex, wt = weight)
summary
```

```{r}
summary %>% 
  ggplot(aes(age, n, colour = sex)) + 
  geom_line() + 
  labs(y = "Estimated number of injuries")
```



```{r}
summary <- selected %>% count(age, sex, wt = weight) %>% left_join(population, by = c("age", "sex")) %>% 
                        mutate(rate = n / population * 1e4)

summary
```

```{r}
summary %>% 
  ggplot(aes(age, rate, colour = sex)) + 
  geom_line(na.rm = TRUE) + 
  labs(y = "Injuries per 10,000 people")
```


```{r}
selected %>% 
  sample_n(10) %>% 
  pull(narrative)
```


```{r}
ui <- fluidPage(
  titlePanel("Example 1"),
  fluidRow(
    column(6,selectInput("code", "Product", setNames(products$prod_code, products$title))),
    column(6,shinythemes::themeSelector())),
  fluidRow(
    column(3, tableOutput("diag")),
    column(3, tableOutput("body_part")),
    column(3, tableOutput("location"))),
  fluidRow(
    column(12, plotOutput("age_sex")))
)

server <- function(input, output, session) {
  selected <- reactive(injuries %>% filter(prod_code == input$code))

  output$diag <- renderTable(selected() %>% count(diag, wt = weight, sort = TRUE))
  output$body_part <- renderTable(selected() %>% count(body_part, wt = weight, sort = TRUE))
  output$location <- renderTable(selected() %>% count(location, wt = weight, sort = TRUE))

  summary <- reactive({
    selected() %>% count(age, sex, wt = weight) %>% left_join(population, by = c("age", "sex")) %>%
      mutate(rate = n / population * 1e4)
  })

  output$age_sex <- renderPlot({
    summary() %>% ggplot(aes(age, n, colour = sex)) + geom_line() + labs(y = "Estimated number of injuries")
  }, res = 96)
}



shinyApp(ui, server)

```

```{r}
injuries %>%
  mutate(diag = fct_lump(fct_infreq(diag), n = 5)) %>%
  group_by(diag) %>%
  summarise(n = as.integer(sum(weight)))
```



```{r}
count_top <- function(df, var, n = 5) {
  df %>%
    mutate({{ var }} := fct_lump(fct_infreq({{ var }}), n = n)) %>%
    group_by({{ var }}) %>%
    summarise(n = as.integer(sum(weight)))
}
```

```{r}
ui <- fluidPage(
  titlePanel("Example 2"),
  fluidRow(column(8, selectInput("code", "Product", choices = setNames(products$prod_code, products$title), width = "100%"))),
  fluidRow(
    column(4, tableOutput("diag")),
    column(4, tableOutput("body_part")),
    column(4, tableOutput("location"))),
  fluidRow(
    column(12, plotOutput("age_sex")))
)


#<< count_top
count_top <- function(df, var, n = 5) {
  df %>%
    mutate({{ var }} := fct_lump(fct_infreq({{ var }}), n = n)) %>%
    group_by({{ var }}) %>%
    summarise(n = as.integer(sum(weight)))
}
#>>

server <- function(input, output, session) {
  selected <- reactive(injuries %>% filter(prod_code == input$code))

  #<< tables
  output$diag <- renderTable(count_top(selected(), diag), width = "100%")
  output$body_part <- renderTable(count_top(selected(), body_part), width = "100%")
  output$location <- renderTable(count_top(selected(), location), width = "100%")
  #>>

  summary <- reactive({
    selected() %>%
      count(age, sex, wt = weight) %>%
      left_join(population, by = c("age", "sex")) %>%
      mutate(rate = n / population * 1e4)
  })

  output$age_sex <- renderPlot({
    summary() %>%
      ggplot(aes(age, n, colour = sex)) +
      geom_line() +
      labs(y = "Estimated number of injuries")
  }, res = 96)
}

shinyApp(ui, server)
```



```{r}
ui <- fluidPage(
  titlePanel("Example 3"),
  fluidRow(
    column(8,
      selectInput("code", "Product",
        choices = setNames(products$prod_code, products$title),
        width = "100%"
      )
    ),
    column(2, selectInput("y", "Y axis", c("rate", "count")))
  ),
  #>>
  fluidRow(
    column(4, tableOutput("diag")),
    column(4, tableOutput("body_part")),
    column(4, tableOutput("location"))
  ),
  fluidRow(
    column(12, plotOutput("age_sex"))
  ),
  #<< narrative-ui
  fluidRow(
    column(2, actionButton("story", "Tell me a story")),
    column(10, textOutput("narrative"))
  )
  #>>
)

count_top <- function(df, var, n = 5) {
  df %>%
    mutate({{ var }} := fct_lump(fct_infreq({{ var }}), n = n)) %>%
    group_by({{ var }}) %>%
    summarise(n = as.integer(sum(weight)))
}

server <- function(input, output, session) {
  selected <- reactive(injuries %>% filter(prod_code == input$code))

  #<< tables
  output$diag <- renderTable(count_top(selected(), diag), width = "100%")
  output$body_part <- renderTable(count_top(selected(), body_part), width = "100%")
  output$location <- renderTable(count_top(selected(), location), width = "100%")
  #>>

  summary <- reactive({
    selected() %>%
      count(age, sex, wt = weight) %>%
      left_join(population, by = c("age", "sex")) %>%
      mutate(rate = n / population * 1e4)
  })

  #<< plot
  output$age_sex <- renderPlot({
    if (input$y == "count") {
      summary() %>%
        ggplot(aes(age, n, colour = sex)) +
        geom_line() +
        labs(y = "Estimated number of injuries")
    } else {
      summary() %>%
        ggplot(aes(age, rate, colour = sex)) +
        geom_line(na.rm = TRUE) +
        labs(y = "Injuries per 10,000 people")
    }
  }, res = 96)
  #>>

  #<< narrative-server
  output$narrative <- renderText({
    input$story
    selected() %>% pull(narrative) %>% sample(1)
  })
  #>>
}

shinyApp(ui, server)
```

```{r}

```


