---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(vroom)
```


```{r}
ui <- fluidPage(
  shinyFeedback::useShinyFeedback(),
  numericInput("n", "n", value = 10),
  textOutput("half")
)

server <- function(input, output) {
 
}
shinyApp(ui, server)

```



```{r}
ui <- fluidPage(
  numericInput("min", "Minimum", 0),
  numericInput("max", "Maximum", 3),
  sliderInput("n", "n", min = 0, max = 3, value = 1)
)

server <- function(input, output, session) {
  observeEvent(input$min, {
    updateSliderInput(session, "n", min = input$min)
  })  
  observeEvent(input$max, {
    updateSliderInput(session, "n", max = input$max)
  })
}

shinyApp(ui, server)


```



```{r}
ui <- fluidPage(
  sliderInput("x1", "x1", 0, min = -10, max = 10),
  sliderInput("x2", "x2", 0, min = -10, max = 10),
  sliderInput("x3", "x3", 0, min = -10, max = 10),
  actionButton("reset", "Reset")
)

server <- function(input, output, session) {
  observeEvent(input$reset, {
    updateSliderInput(session, "x1", value = 0)
    updateSliderInput(session, "x2", value = 0)
    updateSliderInput(session, "x3", value = 0)
  })
}

shinyApp(ui, server)

```



```{r}
ui <- fluidPage(
  numericInput("n", "Simulations", 10),
  actionButton("simulate", "Simulate")
)

server <- function(input, output, session) {
  observeEvent(input$n, {
    label <- paste0("Simulate ", input$n, " times")
    updateActionButton(session, "simulate", label = label)
  })
}
shinyApp(ui, server)


```



```{r}
sales <- read.csv("sales_data_sample.csv")
ui <- fluidPage(
  selectInput("territory", "Territory", choices = unique(sales$TERRITORY)),
  selectInput("customername", "Customer", choices = NULL),
  selectInput("ordernumber", "Order number", choices = NULL),
  tableOutput("data")
)

server <- function(input, output, session) {
  territory <- reactive({
    filter(sales, TERRITORY == input$territory)
  })
  
  observeEvent(territory(), {
    choices <- unique(territory()$CUSTOMERNAME)
    updateSelectInput(session, "customername", choices = choices) 
  })
  
  customer <- reactive({
    req(input$customername)
    filter(territory(), CUSTOMERNAME == input$customername)
  })
  observeEvent(customer(), {
    choices <- unique(customer()$ORDERNUMBER)
    updateSelectInput(session, "ordernumber", choices = choices)
  })
  
  
  output$data <- renderTable({
    req(input$ordernumber)
    customer() %>% 
      filter(ORDERNUMBER == input$ordernumber) %>% 
      select(QUANTITYORDERED, PRICEEACH, PRODUCTCODE)
  })
}

shinyApp(ui, server)

```



```{r}
ui <- fluidPage(
  numericInput("n", "n", 0)
)
server <- function(input, output, session) {
  observeEvent(input$n,
    updateNumericInput(session, "n", value = input$n + 1)
  )
}

shinyApp(ui, server)

```



```{r}
ui <- fluidPage(
  numericInput("temp_c", "Celsius", NA),
  numericInput("temp_f", "Fahrenheit", NA)
)

server <- function(input, output, session) {
  observeEvent(input$temp_f, 
  {
    c <- round((input$temp_f - 32) * 5 / 9)
    updateNumericInput(session, "temp_c", value = c)
  })
  
  observeEvent(input$temp_c, {
    f <- round((input$temp_c * 9 / 5) + 32)
    updateNumericInput(session, "temp_f", value = f)
  })
}

shinyApp(ui, server)

```



```{r}
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("controller", "Show", choices = paste0("panel", 1:3))
    ),
    mainPanel(
      tabsetPanel(
        id = "switcher",
        type = "hidden",
        tabPanel("panel1", "Panel 1 content"),
        tabPanel("panel2", "Panel 2 content"),
        tabPanel("panel3", "Panel 3 content")
      )
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$controller, {
    updateTabsetPanel(session, "switcher", selected = input$controller)
  })
}
shinyApp(ui, server)

```



```{r}
parameter_tabs <- tabsetPanel(
  id = "params",
  type = "hidden",
  tabPanel("normal",
    numericInput("mean", "mean", value = 1),
    numericInput("sd", "standard deviation", min = 0, value = 1)
  ),
  tabPanel("uniform", 
    numericInput("min", "min", value = 0),
    numericInput("max", "max", value = 1)
  ),
  tabPanel("exponential",
    numericInput("rate", "rate", value = 1, min = 0),
  )
)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("dist", "Distribution", 
        choices = c("normal", "uniform", "exponential")
      ),
      numericInput("n", "Number of samples", value = 100),
      parameter_tabs,
    ),
    mainPanel(
      plotOutput("hist")
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$dist, {
    updateTabsetPanel(session, "params", selected = input$dist)
  }) 
  
  sample <- reactive({
    switch(input$dist,
      normal = rnorm(input$n, input$mean, input$sd),
      uniform = runif(input$n, input$min, input$max),
      exponential = rexp(input$n, input$rate)
    )
  })
  output$hist <- renderPlot(hist(sample()), res = 96)
}

shinyApp(ui, server)

```



```{r}
library(dplyr)
library(ggplot2)
library(shiny)

ui = (fluidPage(
  
  # Application title
  titlePanel("Dynamic Filter Test App"),
  

  sidebarLayout(
    sidebarPanel(
       uiOutput("cutlist"),
       uiOutput("colorlist")
    ),
    
    
    mainPanel(
      dataTableOutput("table")
    )
  )
))

server <- function(input, output, session) 
  {
  raw <- diamonds
  
  
  
  output$cutlist <- renderUI({
    
    cutlist <- sort(unique(as.vector(raw$cut)), decreasing = FALSE)
    cutlist <- append(cutlist, "All", after =  0)
    selectizeInput("cutchoose", "Cut:", cutlist)
    
  })
  
  
  output$colorlist <- renderUI({
    
    colorlist <- sort(unique(as.vector(raw$color)), decreasing = FALSE)
    colorlist <- append(colorlist, "All", 0)
    selectizeInput("colorchoose", "color:", colorlist)
    
  }) 
  
  
  data <- reactive({
    
  req(input$colorchoose)
  req(input$cutchoose)
    
    
  if(input$colorchoose == "All") {
      
      filt1 <- quote(color != "@?><")
      
      
    } else {
      
      filt1 <- quote(color == input$colorchoose) 
      
    }
    
    
    if (input$cutchoose == "All") {
      
      filt2 <- quote(cut != "@?><")
      
      
    } else {
      
      filt2 <- quote(cut == input$cutchoose)
      
    }
    
    
    
    raw %>%
      filter_(filt1) %>%
      filter_(filt2)
    
  })
  
  
  output$table <- renderDataTable({
    
    
  data()
  })
  
}
shinyApp(ui, server)


```



```{r}
library(shiny)
library(shinythemes)
library(dplyr)
library(DT)
library(here)

load(here::here('movies.RData'))

min_year <- min(movies$thtr_rel_year)
max_year <- max(movies$thtr_rel_year)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(width = 2,
                 selectInput(
                   inputId = "i_title_type",
                   label = "Title type:",
                   choices = c("All", unique(as.character(movies$title_type))),
                   selected = "All"
                 ),
                 
                 selectInput(
                   inputId = "i_genre",
                   label = "Genre:",
                   choices = c("All", unique(as.character(movies$genre))),
                   selected = "All"
                 ),
                 
                 selectInput(
                   inputId = "i_studio",
                   label = "Studio:",
                   choices = c("All", unique(as.character(movies$studio))),
                   selected = "All"
                 ),

                 selectInput(
                   inputId = "i_mpaa_rating",
                   label = "MPAA rating:",
                   choices = c("All", unique(as.character(movies$mpaa_rating))),
                   selected = "All"
                 ),

                 sliderInput(
                   inputId = "i_year",
                   label = "Year", min = min_year, max = max_year,
                   sep = "",
                   value = c(1995, 2000)

                 ),
                 
                 br(), 
                 
                 actionButton('select', 'Select'),
                 
                 hr(),
                 
                 downloadButton("download", "Download results")
                 
    ),
    
    mainPanel(width = 10,
              DT::dataTableOutput(outputId = "mtable")
    )
  )
)



server <- function(input, output) {
  
  filtered_title_type <- reactive({
    if(input$i_title_type == "All"){
      movies
    } else {
      movies %>%
        filter(title_type == input$i_title_type)
    }
  })
  
  filtered_genre <- reactive({
    if(input$i_genre == "All"){
      filtered_title_type()
    } else {
      filtered_title_type() %>% 
        filter(genre == input$i_genre)
    }
  })
  
  filtered_studio <- reactive({
    if(input$i_studio == "All"){
      filtered_genre()
    } else {
      filtered_genre() %>% 
        filter(studio == input$i_studio)
    }
  })
  
  filtered_rating <- reactive({
    if(input$i_mpaa_rating == "All"){
      filtered_studio()
    } else {
      filtered_studio() %>% 
        filter(mpaa_rating == input$i_mpaa_rating)
    }
  })
  
  filtered_year <- reactive({
    filtered_rating() %>% 
      filter(thtr_rel_year >= input$i_year[1] & thtr_rel_year <= input$i_year[2]) %>% 
      select(title:thtr_rel_year)
  })
  
  fully_filtered <- eventReactive(input$select, {
    filtered_year()
  })
  
  output$mtable <- DT::renderDataTable({
    DT::datatable(data = fully_filtered(), options = list(pageLength = 10),
                  rownames = FALSE, class = 'display', escape = FALSE)
    
  })
  
  output$download <- downloadHandler(
    filename = function() {
      "movie-results.csv"
    },
    content = function(con) {
      write.csv(fully_filtered(), con)
    }
  )
}

# Run the application 
shinyApp(ui = ui, server = server)
```



```{r}
iris$Species

# We can also use `with` for that
with(iris, Species) 

# We are interested in more complicated subsetting though. Want to have all rows
# with 'setosa'
with(iris, Species %in% 'setosa')
iris[with(iris, Species %in% 'setosa'), ]

# Now 'setosa' with some more condition
iris[with(iris, Species %in% 'setosa' & Sepal.Length > 5.3), ]


# That works perfectly. There is, however, an another way doing the exact thing in r.
# We can input the subsetting condition as a character string, then change it to 
# the `expression` and `eval`uate it.

cond_str <- paste0("with(iris, Species %in% 'setosa' & Sepal.Length > 5.3)")
cond_str
# which is the same as
cond_str <- paste0("with(iris, ", "Species %in% ", "'", "setosa", "'", " & ", 
                   "Sepal.Length > ", "5.3", ")")
cond_str

# This second approach will prove very powerful since we will replace "setosa"
# with, say, `input$species` later on.


cond <- parse(text = cond_str)
cond
eval(cond)
iris[eval(cond), ] # √
```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```

